name: Build Logic App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package
      run: (cd src/LogicAppsStandardDemo; mkdir -p ../../output; zip -r ../../output/workflow.zip .)
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: workflow
        path: ./output/
        retention-days: 1