name: Build Logic App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package
      run: (cd src/LogicAppsStandardDemo; mkdir -p ../../output; zip -r ../../output/workflow.zip .)
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: workflow
        path: ./output/
        retention-days: 1

  deploy-dev:
    name: Deploy in Dev
    runs-on: ubuntu-latest
    needs: [build]
    env:
      NAME: dev
      LA_NAME: mysamplelogicapp-dev
      RG: logicapp-dev
      LOCATION: eastus
    steps:
    - name: Checkout
      uses: actions/checkout@v1    
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Create Resource Group
      uses: azure/CLI@v1
      with:
        inlineScript: |
          if [ $(az group exists --name ${{ env.RG }}) = false ]; then
              az group create --name ${{ env.RG }} --location ${{ env.LOCATION }}
          fi

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"

    # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RG }}
        deploymentName: azure-${{ env.NAME }}-${{ steps.date.outputs.date }}
        template: ./src/ArmTemplates/azure.json
        parameters: name=${{ env.LA_NAME }} environmentName=${{ env.NAME }}
