name: Test Java 17

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/java-test.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
